In [10]:
import numpy as np
np.set_printoptions(precision=3,suppress=True)

import dedalus_sphere.jacobi128 as Jacobi
import dedalus_sphere.ball128 as Ball

In [12]:
n = 5
# Boundary with Chebyshev T Polynomials
a, b = -1/2, -1/2
print(Jacobi.operator('z=-1',n,a,b))
print(Jacobi.operator('z=+1',n,a,b))

# Boundary with Chebyshev U Polynomials
a, b = +1/2, +1/2
print(Jacobi.operator('z=-1',n,a,b))
print(Jacobi.operator('z=+1',n,a,b))

# Different parameters
a, b = 1, 3
print(Jacobi.operator('z=-1',n,a,b))
print(Jacobi.operator('z=+1',n,a,b))



[ 0.564 -0.798  0.798 -0.798  0.798 -0.798]
[0.564 0.798 0.798 0.798 0.798 0.798]
[ 1.596 -3.192  4.787 -6.383  7.979 -9.575]
[1.596 3.192 4.787 6.383 7.979 9.575]
[   4.472  -16.733   42.426  -87.75   159.625 -265.631]
[ 4.472  8.367 12.728 17.55  22.804 28.46 ]
